sonar.projectKey=dresogo_Karriko
sonar.organization=dresogo

sonar.sources=src
sonar.exclusions=karriko_flutter/**,node_modules/**,**/*.test.ts,**/*.spec.ts,.next/**,prisma/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
